// svelte-ui/src/lib/components/modules/BodySection.svelte
<script lang="ts">
  import type { BodySection } from "$lib/generated-graphql";
  import PortableText from "../PortableText.svelte";

  export let blockData: BodySection;
  const onlyOneEl = blockData?.contentRaw?.length === 1;
</script>

<section class="body-section container" class:onlyOneEl>
  <PortableText content={blockData.contentRaw} />
</section>

<style>
  .body-section {
    display: grid;
  }
  .body-section:not(.onlyOneEl, :first-of-type) {
    margin: 20vh auto;
  }

  .body-section:first-of-type {
    padding-top: var(--spacing-lg);
  }
</style>

// gatsby-ui/src/components/modules/BodySection.tsx
import styled from '@emotion/styled';
import { SanityBodySection } from '../../../graphql-types';
import BlockContent from '../PortableText';

const BodySectionStyles = styled.section`
  display: grid;

  &:not(&.only-one-el, :first-of-type) {
    margin: 20vh auto;
  }

  &first-of-type {
    padding-top: var(--spacing-lg);
  }
`;

export default function BodySection({ props }: { props: SanityBodySection }) {
  const onlyOneEl = props?._rawContent?.length === 1;

  return (
    <BodySectionStyles
      className={`body-section container ${(onlyOneEl && 'only-one-el') || ''}`}
    >
      <BlockContent block={props?._rawContent} />
    </BodySectionStyles>
  );
}
