// gatsby-ui/src/components/PortableText.tsx
import { ReactElement } from "react"
import PortableText from "react-portable-text"
import { SanityLinkCreator } from "../../graphql-types"
import CallToAction from "./CallToAction"


const serializers = {
  linkCreator: (props: SanityLinkCreator) : ReactElement<SanityLinkCreator> => {
  return (
    <CallToAction cta={props}  />
  )}
}


const BlockContent = ({block}: {block: [object]}) => {
  return (
    <PortableText serializers={serializers} content={block} />
  )
}

export default BlockContent

// svelte-ui/src/lib/components/PortableText.svelte
<script lang="ts">
  import BlockContent from "@portabletext/svelte";
  import CallToAction from "./CallToAction.svelte";
  export let content;

  const blockSerializers = {
    types: {
      linkCreator: CallToAction
    },
  };
</script>

<BlockContent blocks={content} serializers={blockSerializers} />
